version: 2.0
jobs:
  build:
    machine:
      image: circleci/classic:latest
    branches:
          only:
            - circleci
    steps:
      - run:
          name: update
          command: |
            sudo apt-get update;
            
      - checkout
      - run:
          name: write credentials
          command: |
            touch congig1.php
            pwd
            cat << EOF > config1.php
            <?php
            username="$usernae";
            host="$host";
            ?>
            EOF
            ls
            echo "break"
            cat config1.php
