version: 2.0
jobs:
  build:
    machine:
      image: circleci/classic:latest
    branches:
          only:
            - circleci
    steps:
      - run:
          name: write credentials
          command: |
            cat << EOF > config.php
            <?php
            $username="$USERNAME";
            $password="$password";
            ?>
            EOF

      - checkout
      - run:
          name: check credentials1
          command: echo "testing"
         
