version: 2.0
jobs:
  build:
    machine:
      image: circleci/classic:latest
    branches:
          only:
            - circleci
    steps:
      - run:
          name: check credentials
          command: |
            sudo apt-get update;
            echo ${username}
            echo "shubham"
      - checkout
      - run:
          name: check credentials1
          command: echo ${password}
                   echo "kumar"
         