version: 2.0
jobs:
  build:
    machine:
      image: circleci/classic:latest
    branches:
          only:
            - circleci
    steps:
      - run:
          name: write credentials
          command: |
            touch config1.php
            pwd
            cat << EOF > config1.php
            <?php
            username="$USERNAME";
            password="$password";
            ?>
            EOF

      - checkout
     
         
